import type { PreviewQuestion } from "@/lib/seed-data";

export const KENYA60_PREVIEW_QUESTIONS: PreviewQuestion[] = [
  {
    id: "ke60-1",
    question: "Kenya marked 60 years of independence in 2023. Roughly which year did Kenya become independent?",
    options: ["1960", "1963", "1978", "1982"],
    answer: "1963",
    explanation: "Kenya became independent on 12 December 1963 (Republic Day followed in 1964).",
    difficulty: "easy",
  },
  {
    id: "ke60-2",
    question: "Kenya’s national motto is “Harambee”, which best captures its meaning in everyday civic life?",
    options: [
      "Let us compete against each other",
      "Let us pull together / work together",
      "Let us wait for external help",
      "Let us privatize public goods",
    ],
    answer: "Let us pull together / work together",
    explanation: "Harambee expresses community self-help and collective effort toward national goals.",
    difficulty: "easy",
  },
  {
    id: "ke60-3",
    question: "Which city is the constitutional capital of Kenya?",
    options: ["Mombasa", "Nairobi", "Kisumu", "Nakuru"],
    answer: "Nairobi",
    explanation: "Nairobi is Kenya’s capital city and the seat of the national government.",
    difficulty: "easy",
  },
  {
    id: "ke60-4",
    question: "Kenya is a republic with a Bill of Rights in its Constitution. What is the main purpose of the Bill of Rights?",
    options: [
      "To list government holidays",
      "To protect fundamental rights and freedoms",
      "To appoint county governors",
      "To set school fees",
    ],
    answer: "To protect fundamental rights and freedoms",
    explanation: "The Bill of Rights protects human rights and guides law and policy in Kenya.",
    difficulty: "medium",
  },
  {
    id: "ke60-5",
    question: "Kenya’s devolved system created county governments. What is a key benefit counties are meant to improve?",
    options: [
      "Centralizing all revenue in one ministry",
      "Bringing services and decisions closer to citizens",
      "Removing public participation in budgeting",
      "Replacing national elections",
    ],
    answer: "Bringing services and decisions closer to citizens",
    explanation: "Devolution aims to improve local service delivery, accountability, and citizen participation.",
    difficulty: "medium",
  },
  {
    id: "ke60-6",
    question: "Kenya is known for wildlife conservation. Which pair best describes a common conservation challenge and a constructive response?",
    options: [
      "Human-wildlife conflict; community conservancies and corridors",
      "Poaching; ignore enforcement and reduce patrols",
      "Habitat loss; ban tourism completely everywhere",
      "Climate shocks; deny adaptation planning",
    ],
    answer: "Human-wildlife conflict; community conservancies and corridors",
    explanation: "Kenya’s conservation model often combines protection, tourism benefits, and community stewardship.",
    difficulty: "medium",
  },
  {
    id: "ke60-7",
    question: "Kenya’s economy is diverse, but which sector employs a large share of Kenyans and remains central to livelihoods?",
    options: ["Only mining", "Agriculture and the informal economy", "Only offshore banking", "Only space technology"],
    answer: "Agriculture and the informal economy",
    explanation: "Agriculture and informal trade/services remain major employers and resilience buffers for households.",
    difficulty: "easy",
  },
  {
    id: "ke60-8",
    question: "Kenya’s Vision 2030 emphasized transforming Kenya into a newly industrializing, middle-income country. Which pillar is NOT one of its three broad pillars?",
    options: ["Economic", "Social", "Political", "Security"],
    answer: "Security",
    explanation: "Vision 2030 is commonly organized around Economic, Social, and Political pillars (security supports them, but it is not the third named pillar).",
    difficulty: "hard",
  },
  {
    id: "ke60-9",
    question: "Which statement best describes Kenya’s regional role in East Africa?",
    options: [
      "Kenya is landlocked and isolated from regional trade",
      "Kenya hosts a major port (Mombasa) and is a trade gateway in the region",
      "Kenya has no customs cooperation with neighbors",
      "Kenya’s borders are closed to all regional students",
    ],
    answer: "Kenya hosts a major port (Mombasa) and is a trade gateway in the region",
    explanation: "Mombasa’s port and transport corridors connect Kenya to regional and global markets.",
    difficulty: "medium",
  },
  {
    id: "ke60-10",
    question: "Kenya@60 is a good moment for families to discuss civic responsibility. Which action best models responsible citizenship?",
    options: [
      "Paying taxes and participating in public participation forums",
      "Spreading unverified rumors online",
      "Avoiding all community meetings",
      "Bribing officials to skip queues",
    ],
    answer: "Paying taxes and participating in public participation forums",
    explanation: "Responsible citizenship includes lawful compliance and constructive engagement in public processes.",
    difficulty: "easy",
  },
];
